### PR TITLE
Vulcan and Cyborg Ruby

### PR DESCRIPTION
**Pull request by gw90**
I have added a Vulcan Ruby and a Cyborg Ruby.

### CODE REVIEW

**Comment by winghouchan** [comment]
Hello @gw90, please resolve conflicts before we can consider this for merging. :smile:

**Comment by brks** [comment]
Wing, we're supposed to fix that :tongue:

**Comment by brks** [comment]
@gw90 Please note that I had to remove Vulcan Ruby because the sizings were incorrect, however great work with Cyborg Ruby! Now live on http://rb.yrs.io

**Comment by winghouchan** [comment]
@gw90 hasn't provided a Twitter account leaving [`Line 44 index.html`](https://github.com/gw90/rubys-threads/commit/373a92700eb43c9fd16e368be505b0c690397d72#diff-eacf331f0ffc35d4b482f1d15a887d3bR44) without a link and also with a "N/A" in the anchor text.

We can use @gw90's name and web address as a replacement.

**Comment by brks** [comment]
Go for it @winghouchan

**Pull request merged**
